name: Deploy Cloudflare Workers

inputs:
  working_dir:
    required: true
    type: string
  article_data_path:
    required: true
    type: string
  user_data_path:
    required: true
    type: string
  build_data_path:
    required: true
    type: string
  project_name:
    required: true
    type: string
  site_url:
    required: true
    type: string
  cloudflare_account_id:
    required: true
    type: string
  cloudflare_api_token:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Copy articles
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: |
        mkdir -p contents/articles
        cp -r ${{ inputs.article_data_path }}/* contents/articles/

    - name: Copy users
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: |
        mkdir -p contents/users
        cp -r ${{ inputs.user_data_path }}/* contents/users/

    - shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: |
        mkdir public
        cp -r ${{ inputs.build_data_path }}/* public/

    - shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: |
        mkdir -p public/raw__/articles
        mv public/articles public/raw__/articles/html
        cd public/raw__/articles/html
        find . -type f -name index.html -print0 | while IFS= read -r -d '' file; do mv "$file" "${file%/*}.html"; done

    - shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: |
        mkdir -p public/raw__/users
        mv public/users public/raw__/users/html
        cd public/raw__/users/html
        find . -type f -name index.html -print0 | while IFS= read -r -d '' file; do mv "$file" "${file%/*}.html"; done

    - shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: tree -a

    - name: Enable corepack
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: corepack enable

    - uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install Node dependencies
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: pnpm install

    - name: Build site
      shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: PUBLIC_KEY_FILE=test_config/public-key-for-test.pem pnpm run build

    - shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: tree -a dist

    - shell: bash
      working-directory: ${{ inputs.working_dir }}
      run: mv dist crates/cloudflare_workers/public

    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown

    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        workingDirectory: ${{ inputs.working_dir }}/crates/cloudflare_workers
        accountId: ${{ inputs.cloudflare_account_id }}
        apiToken: ${{ inputs.cloudflare_api_token }}
        preCommands: |
          ./setup_resources.sh "${{ inputs.project_name }}" "${{ inputs.site_url }}"
          cat wrangler.toml
        command: deploy
