url: https://sharkey.test/
port: 3000

db:
  host: sharkey_db
  port: 5432
  db: misskey
  user: example-misskey-user
  pass: example-misskey-pass

dbReplications: false
redis:
  host: sharkey_redis
  port: 6379

fulltextSearch:
  provider: sqlLike

id: 'aidx'

proxyBypassHosts:
  - api.deepl.com
  - api-free.deepl.com
  - www.recaptcha.net
  - hcaptcha.com
  - challenges.cloudflare.com

proxyRemoteFiles: true
signToActivityPubGet: true
attachLdSignatureForRelays: true
checkActivityPubGetSignature: false
