name = "fblog-system"
main = "build/worker/shim.mjs"
compatibility_date = "2025-06-07"

[build]
command = "cargo install -q worker-build && worker-build --release"

[assets]
directory = "./public/"
binding = "ASSETS"

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'blog-system'

[vars]
URL = "https://blog.test"
PRIVATE_KEY_PEM = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIXpGBYnA37FKA\naFmZXeNrIbIWkvqC3TZEiRO5JB4fFoLP9wF6lvkHVePmDmyJ9UvKr2UmHVL1VF+f\nWI6wKJIb0k1KS8QuG5ZheptMluvWfs/812h9YolzhBB6yxnjWueiMceaNwyNbdDh\nHdfB7QNFJIoioJ9yn7zBbOgUOEY3fbuxxMr1eUx57xpxpa/MoGDqBnEQSHi7Tf5H\nOeC3L0t0zHTucfH5p/apW/MuCeuo/A6ZKqKYVKhSYcSsL9SNJMXzv97HmRxj9FbL\nI83LJBeXTzsKktU43c2pKELh+0WuZHRMAAfJlNBnEX9OflaBG/YPBdoMxN0L5PvN\nHsyuoEibAgMBAAECggEAUDmNCMDhLYLxhXhCZ6Wv6LUVGPTAWKU5lTdNLlPHu6rH\ntXywmuTX0JgTJ4me653LOtv/I8OZ86BUqPhMKTwVRA5v489yPQPOsjjk9UV4J+me\nXR3iOFG7twSplIC9XMqI8+f6g0SHQhk2COxp9rtvE8ANjs/BB6Ptb4SrZ20gsBZy\nBgpEqKfjJweh4weazI+AJH/iMnA/HOMK8iIhdrDe8HMRDl5NpPEa2gW7/n0eOpo5\n7lLDuG6RHLAxI2PxjIykoYfBo4txx99SWCCUSRTqKhqAjdNDjv+DGjWD2gAxDeBI\nij9r8XL6VNeHCcJ2gHF4Mg0VtGPXi4+6gMr7mRHYAQKBgQDssidH78BtzxSdMNEl\n7gvxhIkyeEn51dXZbxBiGoPSdNBMT+83GJs3NOUYrxdJJ17RUSccGBFYyoMgJW/p\nZtwMCgrAohrXJxr+RyhGhHgklK85r9oX0zG3MiYIrfrRiTpH1kSe4ERqMuBOYjmQ\nIn/CNWHhn4xx3CYPvk1D0tu6+QKBgQDYtfkxWtQ6TqaT8IDkNZTvg3Wvvebo6iGW\n5rUqs5fn0PrlK8kDRtZtjR85XKxsQ9+JX53izTJb6KMw0rg4uahnCv3UC8P+fj49\nwA0z02HFcHjgfh5YiTuFWvuwr5dywleJFD/gUUkak4y0WDIKZlZXt982OhVWHoEM\nXXAqOUuRMwKBgQDS+jlpNZsgReTp+Al09apPrQNdqTrHJoNnPEguKdQ2U0kXvGhN\ng/FWVB+g0PDAlAdALEXgFNPhgSFAFh6avMSHNqw+6D9kZ8b3wBV2Rb2RXbaShNyx\nP96gnGKqeemHu/nm7mZb9ysEPjURqRwGDbozMcH9iml1U/XZMpdMTTbugQKBgQC8\nojmU4nEVh9yrrY8kFhfcHFvWa8CRQSuXxJ4x2z4AxQF/dgt01LZViZ+COM7FNpdf\nZmFySBbrtaZHG0TL659QglrLtqoV3iGjcoaLdBYI3Iv7LQyRGHM88yNeepmjhNLZ\nOU0Ynui5P3IckSCNuOKzXBPpicmEuuytrK+zsUe7zQKBgAStm6iN2XEpPvgqKQZ7\noltkbZ9NZ74UWFQi0tWoRJRNe7lRs7PFc2b5cgr+2CnPnSsl8CdqTDSyytlqQtVM\nDn+JIZfUlBB04YAbZD+51eVwQNT5L428HLclKy0InKjxsft+lfIde/XnBG+N8lfK\nO88SYjw60IP5vXl5DRhvvsZE\n-----END PRIVATE KEY-----\n"

[[d1_databases]]
binding = "FOLLOWERS_DB"
database_name = "followers"
database_id = "00000000-0000-0000-0000-000000000000"

[[queues.producers]]
queue = "job_queue"
binding = "JOB_QUEUE"

[[queues.consumers]]
queue = "job_queue"
max_batch_size = 10
max_batch_timeout = 30

[observability.logs]
enabled = true
