name = "fedi-blog-system"
main = "build/worker/shim.mjs"
compatibility_date = "2025-02-14"

[build]
command = "cargo install -q worker-build && worker-build --release"

[assets]
directory = "./public/"
binding = "ASSETS"
run_worker_first = true

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'blog-system'

[vars]
URL = "http://blog.localhost"

[observability.logs]
enabled = true
