name = "fblog-system"
main = "build/worker/shim.mjs"
compatibility_date = "2025-06-07"

[build]
command = "cargo install -q worker-build && worker-build --release"

[assets]
directory = "./public/"
binding = "ASSETS"

[[r2_buckets]]
binding = 'R2_BUCKET'
bucket_name = 'blog-system'

[vars]
URL = "https://blog.test"

[observability.logs]
enabled = true
