name: 'Default Author'
bio: 'This is the default author bio. This author writes about various topics and has been contributing to this blog for some time.'
avatar: '/image5.png'
website: 'https://example.com'
twitter: 'defaultauthor'
github: 'defaultauthor'
