name: Sample build VRT Capture

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  capture:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install Node dependencies
        run: pnpm install --frozen-lockfile

      - name: Capture sample build
        run: bash ./.github/scripts/capture_sample_build_vrt_data.sh

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sample-build-vrt-data
          path: dist

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          SUCCESSOR_NAME: ${{ github.event_name == 'pull_request' && 'pr_checks' || 'publish_baseline' }}
        with:
          script: |
            const { owner, repo } = context.repo;
            const sha = context.payload.pull_request?.head?.sha || context.sha;

            await github.rest.repos.createCommitStatus({
              owner, repo, sha,
              state: "pending",
              context: `sample-build-vrt-report / ${process.env.SUCCESSOR_NAME}`,
            });
